version: '3.4'

services:
  docker-db:
    ports:
      - 1433:1433
    networks:
      - ngrok-net
    image: "mcr.microsoft.com/mssql/server"
    container_name: docker-db
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
      
  ngrok:
    ports:
      - 4040:4040
    image: "gtriggiano/ngrok-tunnel"
    container_name: ngrok
    stdin_open: true
    tty: true
    environment:
        TARGET_HOST: "192.168.99.100"
        TARGET_PORT: 27015
      
  api:
    ports:
      - 27015:27015
    networks:
      - ngrok-net
    environment:
      ASPNETCORE_URLS: http://+:27015
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - docker-db
      
networks:
  ngrok-net:
    external: true